[features]
seeds = false
[programs.devnet]
first_app = "GkztqhmR3FE9iFrAyCHDcVMfCJcJ56HCxmoTtKWTTtMn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/vuanhtu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
